# Using a Dockerfile in case we want to modify the bootstrap running environment
# That said, please refrain from modifying the bootstrap running environment.  
# Put in a PR to the running container (below) instead.
FROM infrastructurebuilder/minimal_alma_dc:latest
